// Generated by JFlex 1.9.1 http://jflex.de/  (tweaked for IntelliJ platform)
// source: _GnoLexer.flex

package com.github.intellij.gno.lexer;

import com.intellij.lexer.FlexLexer;
import com.intellij.psi.tree.IElementType;

import static com.intellij.psi.TokenType.BAD_CHARACTER;
import static com.intellij.psi.TokenType.WHITE_SPACE;
import static com.github.intellij.gno.psi.GnoTypes.*;


public class _GnoLexer implements FlexLexer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\25\u0100\1\u0200\11\u0100\1\u0300\17\u0100\1\u0400\247\u0100"+
    "\10\u0500\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\2\3\1\4\22\0\1\1\1\5"+
    "\1\6\2\0\1\7\1\10\1\0\1\11\1\12\1\13"+
    "\1\14\1\15\1\16\1\17\1\20\12\21\1\22\1\23"+
    "\1\24\1\25\1\26\2\0\32\27\1\30\1\31\1\32"+
    "\1\33\1\27\1\0\1\34\1\27\1\35\1\36\1\37"+
    "\1\40\1\41\1\42\1\43\1\27\1\44\1\45\1\46"+
    "\1\47\1\50\1\51\1\27\1\52\1\53\1\54\1\55"+
    "\1\56\1\57\1\27\1\60\1\27\1\61\1\62\1\63"+
    "\7\0\1\3\32\0\1\1\u01df\0\1\1\177\0\13\1"+
    "\35\0\2\3\5\0\1\1\57\0\1\1\240\0\1\1"+
    "\377\0\u0100\64";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1536];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\1\1\4\1\5\1\6"+
    "\1\7\1\10\1\11\1\12\1\13\1\14\1\15\1\16"+
    "\1\17\1\20\1\21\1\22\1\23\1\24\1\25\1\26"+
    "\1\27\14\24\1\30\1\31\1\32\1\33\1\0\1\34"+
    "\1\0\1\35\1\0\1\36\1\37\1\40\1\41\1\42"+
    "\1\43\7\24\1\44\1\45\12\24\1\46\1\36\5\24"+
    "\1\47\3\24\1\50\6\24\1\51\1\52\1\53\3\24"+
    "\1\54\1\55\7\24\1\56\1\57\1\24\1\60\10\24"+
    "\1\61\2\24\1\62\1\63\1\64\1\65\1\66\1\24"+
    "\1\67\1\24\1\70";

  private static int [] zzUnpackAction() {
    int [] result = new int[128];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\65\0\152\0\237\0\324\0\65\0\u0109\0\65"+
    "\0\65\0\65\0\65\0\65\0\65\0\65\0\u013e\0\u0173"+
    "\0\65\0\65\0\u01a8\0\u01dd\0\u0212\0\u0247\0\65\0\65"+
    "\0\65\0\u027c\0\u02b1\0\u02e6\0\u031b\0\u0350\0\u0385\0\u03ba"+
    "\0\u03ef\0\u0424\0\u0459\0\u048e\0\u04c3\0\65\0\u04f8\0\65"+
    "\0\65\0\324\0\65\0\u052d\0\65\0\u0562\0\u0597\0\65"+
    "\0\65\0\65\0\65\0\65\0\u05cc\0\u0601\0\u0636\0\u066b"+
    "\0\u06a0\0\u06d5\0\u070a\0\u0247\0\u0247\0\u073f\0\u0774\0\u07a9"+
    "\0\u07de\0\u0813\0\u0848\0\u087d\0\u08b2\0\u08e7\0\u091c\0\65"+
    "\0\u0562\0\u0951\0\u0986\0\u09bb\0\u09f0\0\u0a25\0\u0247\0\u0a5a"+
    "\0\u0a8f\0\u0ac4\0\u0247\0\u0af9\0\u0b2e\0\u0b63\0\u0b98\0\u0bcd"+
    "\0\u0c02\0\u0247\0\u0247\0\u0247\0\u0c37\0\u0c6c\0\u0ca1\0\u0247"+
    "\0\u0247\0\u0cd6\0\u0d0b\0\u0d40\0\u0d75\0\u0daa\0\u0ddf\0\u0e14"+
    "\0\u0247\0\u0247\0\u0e49\0\u0247\0\u0e7e\0\u0eb3\0\u0ee8\0\u0f1d"+
    "\0\u0f52\0\u0f87\0\u0fbc\0\u0ff1\0\u0247\0\u1026\0\u105b\0\u0247"+
    "\0\u0247\0\u0247\0\u0247\0\u0247\0\u1090\0\u0247\0\u10c5\0\u0247";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[128];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\4\3\1\4\1\5\1\6\1\7\1\10\1\11"+
    "\1\12\1\13\1\14\1\15\1\16\1\17\1\20\1\21"+
    "\1\22\1\23\1\24\1\25\1\26\1\27\1\2\1\30"+
    "\1\31\1\26\1\32\1\33\1\34\1\35\1\36\1\26"+
    "\1\37\2\26\1\40\2\26\1\41\1\42\1\43\1\44"+
    "\1\26\1\45\2\26\1\46\1\47\1\50\1\2\66\0"+
    "\4\3\105\0\1\51\37\0\2\52\1\0\1\52\1\0"+
    "\1\52\1\53\22\52\1\54\33\52\10\0\1\55\54\0"+
    "\2\56\3\0\13\56\1\57\43\56\22\0\1\20\67\0"+
    "\1\60\1\61\64\0\1\62\64\0\1\63\1\64\57\0"+
    "\1\26\5\0\1\26\4\0\25\26\25\0\1\26\5\0"+
    "\1\26\4\0\1\65\5\26\1\66\5\26\1\67\10\26"+
    "\25\0\1\26\5\0\1\26\4\0\3\26\1\70\21\26"+
    "\25\0\1\26\5\0\1\26\4\0\11\26\1\71\13\26"+
    "\25\0\1\26\5\0\1\26\4\0\14\26\1\72\4\26"+
    "\1\73\3\26\25\0\1\26\5\0\1\26\4\0\14\26"+
    "\1\74\10\26\25\0\1\26\5\0\1\26\4\0\4\26"+
    "\1\75\5\26\1\76\1\77\11\26\25\0\1\26\5\0"+
    "\1\26\4\0\1\100\24\26\25\0\1\26\5\0\1\26"+
    "\4\0\1\101\24\26\25\0\1\26\5\0\1\26\4\0"+
    "\3\26\1\102\21\26\25\0\1\26\5\0\1\26\4\0"+
    "\3\26\1\103\14\26\1\104\2\26\1\105\1\26\25\0"+
    "\1\26\5\0\1\26\4\0\24\26\1\106\25\0\1\26"+
    "\5\0\1\26\4\0\1\107\24\26\66\0\1\110\2\0"+
    "\2\52\3\0\57\52\1\0\2\56\3\0\13\56\1\111"+
    "\43\56\1\0\2\57\1\0\62\57\21\0\1\26\5\0"+
    "\1\26\4\0\17\26\1\112\5\26\25\0\1\26\5\0"+
    "\1\26\4\0\1\113\24\26\25\0\1\26\5\0\1\26"+
    "\4\0\13\26\1\114\11\26\25\0\1\26\5\0\1\26"+
    "\4\0\4\26\1\115\20\26\25\0\1\26\5\0\1\26"+
    "\4\0\17\26\1\116\5\26\25\0\1\26\5\0\1\26"+
    "\4\0\16\26\1\117\6\26\25\0\1\26\5\0\1\26"+
    "\4\0\13\26\1\120\11\26\25\0\1\26\5\0\1\26"+
    "\4\0\15\26\1\121\7\26\25\0\1\26\5\0\1\26"+
    "\4\0\20\26\1\122\4\26\25\0\1\26\5\0\1\26"+
    "\4\0\15\26\1\123\7\26\25\0\1\26\5\0\1\26"+
    "\4\0\1\26\1\124\23\26\25\0\1\26\5\0\1\26"+
    "\4\0\20\26\1\125\4\26\25\0\1\26\5\0\1\26"+
    "\4\0\11\26\1\126\13\26\25\0\1\26\5\0\1\26"+
    "\4\0\16\26\1\127\6\26\25\0\1\26\5\0\1\26"+
    "\4\0\7\26\1\130\15\26\25\0\1\26\5\0\1\26"+
    "\4\0\15\26\1\131\7\26\25\0\1\26\5\0\1\26"+
    "\4\0\16\26\1\132\6\26\25\0\1\26\5\0\1\26"+
    "\4\0\3\26\1\133\21\26\25\0\1\26\5\0\1\26"+
    "\4\0\13\26\1\134\11\26\25\0\1\26\5\0\1\26"+
    "\4\0\17\26\1\135\5\26\25\0\1\26\5\0\1\26"+
    "\4\0\1\136\2\26\1\137\21\26\25\0\1\26\5\0"+
    "\1\26\4\0\3\26\1\140\21\26\25\0\1\26\5\0"+
    "\1\26\4\0\1\26\1\141\23\26\25\0\1\26\5\0"+
    "\1\26\4\0\14\26\1\142\10\26\25\0\1\26\5\0"+
    "\1\26\4\0\3\26\1\143\21\26\25\0\1\26\5\0"+
    "\1\26\4\0\10\26\1\144\14\26\25\0\1\26\5\0"+
    "\1\26\4\0\21\26\1\145\3\26\25\0\1\26\5\0"+
    "\1\26\4\0\3\26\1\146\21\26\25\0\1\26\5\0"+
    "\1\26\4\0\21\26\1\147\3\26\25\0\1\26\5\0"+
    "\1\26\4\0\20\26\1\150\4\26\25\0\1\26\5\0"+
    "\1\26\4\0\3\26\1\151\21\26\25\0\1\26\5\0"+
    "\1\26\4\0\20\26\1\152\4\26\25\0\1\26\5\0"+
    "\1\26\4\0\21\26\1\153\3\26\25\0\1\26\5\0"+
    "\1\26\4\0\16\26\1\154\6\26\25\0\1\26\5\0"+
    "\1\26\4\0\16\26\1\155\6\26\25\0\1\26\5\0"+
    "\1\26\4\0\16\26\1\156\6\26\25\0\1\26\5\0"+
    "\1\26\4\0\1\157\24\26\25\0\1\26\5\0\1\26"+
    "\4\0\16\26\1\160\6\26\25\0\1\26\5\0\1\26"+
    "\4\0\1\26\1\161\23\26\25\0\1\26\5\0\1\26"+
    "\4\0\1\26\1\162\23\26\25\0\1\26\5\0\1\26"+
    "\4\0\1\26\1\163\23\26\25\0\1\26\5\0\1\26"+
    "\4\0\11\26\1\164\13\26\25\0\1\26\5\0\1\26"+
    "\4\0\20\26\1\165\4\26\25\0\1\26\5\0\1\26"+
    "\4\0\4\26\1\166\20\26\25\0\1\26\5\0\1\26"+
    "\4\0\5\26\1\167\17\26\25\0\1\26\5\0\1\26"+
    "\4\0\13\26\1\170\11\26\25\0\1\26\5\0\1\26"+
    "\4\0\20\26\1\171\4\26\25\0\1\26\5\0\1\26"+
    "\4\0\20\26\1\172\4\26\25\0\1\26\5\0\1\26"+
    "\4\0\6\26\1\173\16\26\25\0\1\26\5\0\1\26"+
    "\4\0\20\26\1\174\4\26\25\0\1\26\5\0\1\26"+
    "\4\0\1\175\24\26\25\0\1\26\5\0\1\26\4\0"+
    "\3\26\1\176\21\26\25\0\1\26\5\0\1\26\4\0"+
    "\1\26\1\177\23\26\25\0\1\26\5\0\1\26\4\0"+
    "\3\26\1\200\21\26\4\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[4346];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String[] ZZ_ERROR_MSG = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\3\1\1\11\1\1\7\11\2\1\2\11"+
    "\4\1\3\11\14\1\1\11\1\1\2\11\1\0\1\11"+
    "\1\0\1\11\1\0\1\1\5\11\23\1\1\11\70\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[128];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private CharSequence zzBuffer = "";

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** Number of newlines encountered up to the start of the matched text. */
  @SuppressWarnings("unused")
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  @SuppressWarnings("unused")
  protected int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  @SuppressWarnings("unused")
  private boolean zzEOFDone;

  /* user code: */
  public _GnoLexer() {
    this((java.io.Reader)null);
  }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public _GnoLexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  public final int getTokenStart() {
    return zzStartRead;
  }

  public final int getTokenEnd() {
    return getTokenStart() + yylength();
  }

  public void reset(CharSequence buffer, int start, int end, int initialState) {
    zzBuffer = buffer;
    zzCurrentPos = zzMarkedPos = zzStartRead = start;
    zzAtEOF  = false;
    zzAtBOL = true;
    zzEndRead = end;
    yybegin(initialState);
  }

  /**
   * Refills the input buffer.
   *
   * @return      {@code false}, iff there was new input.
   *
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {
    return true;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final CharSequence yytext() {
    return zzBuffer.subSequence(zzStartRead, zzMarkedPos);
  }


  /**
   * Returns the character at position {@code pos} from the
   * matched text.
   *
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch.
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer.charAt(zzStartRead+pos);
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * In a wellformed scanner (no or only correct usage of
   * yypushback(int) and a match-all fallback rule) this method
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public IElementType advance() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    CharSequence zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return null;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { return BAD_CHARACTER;
            }
          // fall through
          case 57: break;
          case 2:
            { return WHITE_SPACE;
            }
          // fall through
          case 58: break;
          case 3:
            { return NOT;
            }
          // fall through
          case 59: break;
          case 4:
            { return MODULO;
            }
          // fall through
          case 60: break;
          case 5:
            { return BIT_AND;
            }
          // fall through
          case 61: break;
          case 6:
            { return LPAREN;
            }
          // fall through
          case 62: break;
          case 7:
            { return RPAREN;
            }
          // fall through
          case 63: break;
          case 8:
            { return MUL;
            }
          // fall through
          case 64: break;
          case 9:
            { return PLUS;
            }
          // fall through
          case 65: break;
          case 10:
            { return COMMA;
            }
          // fall through
          case 66: break;
          case 11:
            { return MINUS;
            }
          // fall through
          case 67: break;
          case 12:
            { return DOT;
            }
          // fall through
          case 68: break;
          case 13:
            { return DIV;
            }
          // fall through
          case 69: break;
          case 14:
            { return INT;
            }
          // fall through
          case 70: break;
          case 15:
            { return COLON;
            }
          // fall through
          case 71: break;
          case 16:
            { return SEMICOLON;
            }
          // fall through
          case 72: break;
          case 17:
            { return LESS;
            }
          // fall through
          case 73: break;
          case 18:
            { return ASSIGN;
            }
          // fall through
          case 74: break;
          case 19:
            { return GREATER;
            }
          // fall through
          case 75: break;
          case 20:
            { return IDENTIFIER;
            }
          // fall through
          case 76: break;
          case 21:
            { return LBRACK;
            }
          // fall through
          case 77: break;
          case 22:
            { return RBRACK;
            }
          // fall through
          case 78: break;
          case 23:
            { return BIT_XOR;
            }
          // fall through
          case 79: break;
          case 24:
            { return LBRACE;
            }
          // fall through
          case 80: break;
          case 25:
            { return BIT_OR;
            }
          // fall through
          case 81: break;
          case 26:
            { return RBRACE;
            }
          // fall through
          case 82: break;
          case 27:
            { return NOT_EQUALS;
            }
          // fall through
          case 83: break;
          case 28:
            { return STRING;
            }
          // fall through
          case 84: break;
          case 29:
            { return AND;
            }
          // fall through
          case 85: break;
          case 30:
            { return COMMENT;
            }
          // fall through
          case 86: break;
          case 31:
            { return SHIFT_LEFT;
            }
          // fall through
          case 87: break;
          case 32:
            { return LESS_EQUAL;
            }
          // fall through
          case 88: break;
          case 33:
            { return EQUALS;
            }
          // fall through
          case 89: break;
          case 34:
            { return GREATER_EQUAL;
            }
          // fall through
          case 90: break;
          case 35:
            { return SHIFT_RIGHT;
            }
          // fall through
          case 91: break;
          case 36:
            { return GO;
            }
          // fall through
          case 92: break;
          case 37:
            { return IF;
            }
          // fall through
          case 93: break;
          case 38:
            { return OR;
            }
          // fall through
          case 94: break;
          case 39:
            { return FOR;
            }
          // fall through
          case 95: break;
          case 40:
            { return MAP;
            }
          // fall through
          case 96: break;
          case 41:
            { return VAR;
            }
          // fall through
          case 97: break;
          case 42:
            { return CASE;
            }
          // fall through
          case 98: break;
          case 43:
            { return CHAN;
            }
          // fall through
          case 99: break;
          case 44:
            { return ELSE;
            }
          // fall through
          case 100: break;
          case 45:
            { return FUNC;
            }
          // fall through
          case 101: break;
          case 46:
            { return TYPE;
            }
          // fall through
          case 102: break;
          case 47:
            { return CONST;
            }
          // fall through
          case 103: break;
          case 48:
            { return DEFER;
            }
          // fall through
          case 104: break;
          case 49:
            { return IMPORT;
            }
          // fall through
          case 105: break;
          case 50:
            { return RETURN;
            }
          // fall through
          case 106: break;
          case 51:
            { return SELECT;
            }
          // fall through
          case 107: break;
          case 52:
            { return STRUCT;
            }
          // fall through
          case 108: break;
          case 53:
            { return SWITCH;
            }
          // fall through
          case 109: break;
          case 54:
            { return DEFAULT;
            }
          // fall through
          case 110: break;
          case 55:
            { return PACKAGE;
            }
          // fall through
          case 111: break;
          case 56:
            { return INTERFACE;
            }
          // fall through
          case 112: break;
          default:
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
